// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using PORTAL.DAL.EF;
using PORTAL.DAL.EF.Helper;
using System;

namespace PORTAL.DAL.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181009074526_employeewithOtp")]
    partial class employeewithOtp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.Annotation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Annotation_Id");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DocumentBody");

                    b.Property<string>("FileName")
                        .HasMaxLength(255);

                    b.Property<int?>("FileSize");

                    b.Property<bool>("IsDocument");

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("MimeType")
                        .HasMaxLength(256);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("NoteText");

                    b.Property<string>("ObjectId");

                    b.Property<string>("ObjectName");

                    b.Property<int>("Status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Annotation");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ApplicationAction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("AccessNeeded");

                    b.Property<string>("ActionName");

                    b.Property<string>("ApplicationAction_Id");

                    b.Property<string>("ControllerName");

                    b.Property<string>("Description");

                    b.Property<bool>("IsHttpPOST");

                    b.HasKey("Id");

                    b.ToTable("ApplicationAction");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ApplicationAction_ApplicationPermission", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessType");

                    b.Property<string>("ApplicationActionId");

                    b.Property<string>("ApplicationPermissionId");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationActionId");

                    b.HasIndex("ApplicationPermissionId");

                    b.ToTable("ApplicationAction_ApplicationPermission");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ApplicationPermission", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationPermission_Id");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("ApplicationPermission");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ApplicationRole_ApplicationPermission", b =>
                {
                    b.Property<string>("RoleId");

                    b.Property<string>("ApplicationPermissionId");

                    b.HasKey("RoleId", "ApplicationPermissionId");

                    b.HasIndex("ApplicationPermissionId");

                    b.ToTable("ApplicationRole_ApplicationPermission");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("MiddleName");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("Status");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ClassSchedule", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Schedule");

                    b.HasKey("Id");

                    b.ToTable("ClassSchedule");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.Employee", b =>
                {
                    b.Property<string>("Emp_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Birth_Date");

                    b.Property<string>("Cost_Center");

                    b.Property<string>("Cost_Center_HoD");

                    b.Property<string>("Department");

                    b.Property<string>("Dept_Head_Email");

                    b.Property<string>("Dept_Head_Name");

                    b.Property<string>("Dept_Head_Name_AP");

                    b.Property<string>("Dept_Head_No");

                    b.Property<string>("Division");

                    b.Property<string>("E_Mail");

                    b.Property<string>("Employee_Name_Arabic");

                    b.Property<string>("Employee_Name_English");

                    b.Property<string>("Employee_Spouse");

                    b.Property<string>("Function_Head");

                    b.Property<string>("Gender");

                    b.Property<string>("Grade");

                    b.Property<string>("Hiring_Date");

                    b.Property<string>("ID_Iqama");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Line_Manager_Email");

                    b.Property<string>("Line_Manager_Name");

                    b.Property<string>("Line_Manager_Name_AP");

                    b.Property<string>("Line_Manager_No");

                    b.Property<string>("Mobile");

                    b.Property<string>("Nationality");

                    b.Property<string>("Oracle_Org_Name");

                    b.Property<string>("Position");

                    b.Property<string>("PositionArabic");

                    b.Property<string>("Section");

                    b.Property<string>("Sponsor");

                    b.Property<string>("Termination_Date");

                    b.HasKey("Emp_ID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.OtpCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("EmpId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("EmpId")
                        .IsUnique()
                        .HasFilter("[EmpId] IS NOT NULL");

                    b.ToTable("OtpCode");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.Setting", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.TuitionFee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.HasKey("Id");

                    b.ToTable("TuitionFee");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ViewModels.ApplicationPermissionView", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationPermission_Id");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("StatusName");

                    b.HasKey("Id");

                    b.ToTable("ApplicationPermissionView");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ViewModels.RoleView", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<bool>("IsSysAdmin");

                    b.Property<string>("IsSysAdminName");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<string>("StatusName");

                    b.HasKey("Id");

                    b.ToTable("RoleView");
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<bool>("IsSysAdmin");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int>("Status");

                    b.ToTable("ApplicationRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PORTAL.DAL.EF.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PORTAL.DAL.EF.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PORTAL.DAL.EF.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PORTAL.DAL.EF.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ApplicationAction_ApplicationPermission", b =>
                {
                    b.HasOne("PORTAL.DAL.EF.Models.ApplicationAction", "ApplicationAction")
                        .WithMany("ApplicationAction_ApplicationPermissions")
                        .HasForeignKey("ApplicationActionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PORTAL.DAL.EF.Models.ApplicationPermission", "ApplicationPermission")
                        .WithMany("ApplicationAction_ApplicationPermissions")
                        .HasForeignKey("ApplicationPermissionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.ApplicationRole_ApplicationPermission", b =>
                {
                    b.HasOne("PORTAL.DAL.EF.Models.ApplicationPermission", "ApplicationPermission")
                        .WithMany("ApplicationRole_ApplicationPermissions")
                        .HasForeignKey("ApplicationPermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PORTAL.DAL.EF.Models.ApplicationRole", "ApplicationRole")
                        .WithMany("ApplicationRole_ApplicationPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PORTAL.DAL.EF.Models.OtpCode", b =>
                {
                    b.HasOne("PORTAL.DAL.EF.Models.Employee", "Employee")
                        .WithOne("otpCode")
                        .HasForeignKey("PORTAL.DAL.EF.Models.OtpCode", "EmpId");
                });
#pragma warning restore 612, 618
        }
    }
}
